env:
  node: true

extends:
  - 'airbnb-base'

overrides: []

parserOptions:
  ecmaVersion: latest
  sourceType: module

rules:
  no-console: 0
  indent: off
  import/extensions:
    - error
    - ignorePackages
    - js: always
